package com.stolser.entity;

public enum VideoGenre {
    COMEDY, SHORT, DRAMA, FAMILY, TALK_SHOW, ROMANCE, ANIMATION,
    MUSIC, ACTION, FANTASY, ADVENTURE, SCI_FI, CRIME, GAME_SHOW,
    NEWS, HORROR, MYSTERY, MUSICAL, DOCUMENTARY, THRILLER, REALITY_TV,
    SPORT, HISTORY, WESTERN, WAR, BIOGRAPHY, ADULT;
}
